---
alias: 'Switch on the Lounge Lights at 0530'

trigger:
  - platform: time
    minutes: '/1'
    seconds: 0

condition:
  - condition: time
    after:  '05:30:00'
    before: '05:32:00'

action:
  - service: switch.turn_on
    entity_id: switch.lounge_lamp_light_switch
  - service: notify.telegram
    data:
      message: Lounge Lights On
