alias: 'Check whether we should switch the Lounge Light off'
hide_entity: True

trigger:
  - platform: time
    minutes: '/1'
    seconds: 0

condition:
  - condition: or
    conditions:
      - condition: time
        before: '05:30:00'
        after: '23:00:00'
      - condition: template
        value_template: "{{ states.sun.sun.attributes.elevation >= 0.5 and float(states('sensor.forecastio_cloud_coverage')) <= 85 }}"

action:
  - service: switch.turn_off
    entity_id: switch.lounge_light_switch
