alias: 'Check whether we should switch the Lounge Light on'

trigger:
  - platform: time
    minutes: '/1'
    seconds: 0

condition:
  - condition: and
    conditions:
      - condition: time
        after: '05:30:00'
        before: '23:00:00'
      - condition: template
        value_template: "{{ states.sun.sun.attributes.elevation <= 0.5 or float(states('sensor.forecastio_cloud_coverage')) >= 85 }}"

action:
  - service: switch.turn_on
    entity_id: switch.lounge_light_switch
