---
room lounge:
  name: Lounge
  view: yes
  entities:
    - switch.lounge_lamp_light_switch
    - media_player.firetv_stick
    - media_player.lounge_squeezebox
    - device_tracker.computer_chromebit
    - device_tracker.media_device_firetv_stick
    - device_tracker.media_device_freesat_libreelec_wired
    - device_tracker.media_device_freeview
    - device_tracker.media_device_squeezebox_lounge
    - device_tracker.switchlightlounge
    - device_tracker.games_console_wii
    - device_tracker.games_console_ps3
