---
room playroom:
  name: Playroom Room
  view: yes
  entities:
    - media_player.play_room_squeezebox
    - device_tracker.media_device_squeezebox_playroom
    - device_tracker.router_wifi_playroom
    - device_tracker.printer_hp

